[[pages]]
name = "(ì¡°ì‚¬í‰ê°€)ìµœì¢…ë³´ê³ ì„œ_AI ê¸°ë°˜ êµ­ê°€ì—°êµ¬ê°œë°œì‚¬ì—… í‰ê°€ì§€ì›ì²´ê³„ êµ¬ì¶•ë°©ì•ˆ ì—°êµ¬"
is_section = true
icon = "ğŸ“‘"

[[pages]]
path = "servay_total.py"
name = "Total Dashboard"
icon = "ğŸ“Š"

[[pages]]
path = "servay_each.py"
name = "AutoRAG Dashboard"
icon = "ğŸ”"

[[pages]]
name = "(S&T GPS)AI+íœ´ë¨¸ë…¸ì´ë“œ+ë¡œë´‡+ë™í–¥+ë°+ì‹œì‚¬ì "
is_section = true
icon = "ğŸ¤–"

[[pages]]
path = "gps_total.py"
name = "Total Dashboard"
icon = "ğŸ“Š"

[[pages]]
path = "gps_each.py"
name = "AutoRAG Dashboard"
icon = "ğŸ”"

[[pages]]
name = "[KISTEP ë¸Œë¦¬í”„] ê°ì—¼ë³‘ ë°±ì‹ ì¹˜ë£Œ"
is_section = true
icon = "ğŸ’‰"

[[pages]]
path = "brief_total.py"
name = "Total Dashboard"
icon = "ğŸ“Š"

[[pages]]
path = "brief_each.py"
name = "AutoRAG Dashboard"
icon = "ğŸ”"