[[pages]]
name = "(ì¡°ì‚¬í‰ê°€)ìµœì¢…ë³´ê³ ì„œ_AI ê¸°ë°˜ êµ­ê°€ì—°êµ¬ê°œë°œì‚¬ì—… í‰ê°€ì§€ì›ì²´ê³„ êµ¬ì¶•ë°©ì•ˆ ì—°êµ¬"
is_section = true
icon = "ğŸ“‘"

[[pages]]
path = "page/survey_total.py"
name = "Retrieval Dashboard"
icon = "â–ª"

[[pages]]
path = "page/survey_trial.py"
name = "Trial Dashboard"
icon = "â–«"

[[pages]]
name = "(S&T GPS)AI+íœ´ë¨¸ë…¸ì´ë“œ+ë¡œë´‡+ë™í–¥+ë°+ì‹œì‚¬ì "
is_section = true
icon = "ğŸ¤–"

[[pages]]
path = "page/gps_total.py"
name = "Retrieval Dashboard"
icon = "â–ª"

[[pages]]
path = "page/gps_trial.py"
name = "Trial Dashboard"
icon = "â–«"

[[pages]]
name = "[KISTEP ë¸Œë¦¬í”„] ê°ì—¼ë³‘ ë°±ì‹ ì¹˜ë£Œ"
is_section = true
icon = "ğŸ’‰"

[[pages]]
path = "page/brief_total.py"
name = "Retrieval Dashboard"
icon = "â–ª"

[[pages]]
path = "page/brief_trial.py"
name = "Trial Dashboard"
icon = "â–«"
